spring:
  profoles:
    active:
    - dev
---
spring:
  profoles: dev
  application:
    name: microservicecloud-config-atguigu-dev
---
spring:
  profoles: test
  application:
    name: microservicecloud-config-atguigu-test
