spring:
  profoles:
    active:
    - dev
---
server:
  port:8201
spring:
  profoles: dev
  application:
    name: microservicecloud-config-atguigu-dev
eureka:
  client:
    service-url:
      defaultZone:http://eureka-dev.com:7001/eureka/
