spring:
  profoles:
    active:
    - dev
---
server:
  port:8201
spring:
  profoles: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone:http://eureka-dev.com:7001/eureka/
---
server:
  port:8202
spring:
  profoles: test
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone:http://eureka-dev.com:7001/eureka/
